services:
  mysql:
    image: mariadb:11.6.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang-backend
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql: